# Generated by Django 5.0.6 on 2024-07-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='is_published',
            new_name='published',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='view_count',
            new_name='views',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
