# Generated by Django 5.0.7 on 2024-07-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_version_description_version_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
