# Generated by Django 5.0.7 on 2024-07-20 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_version_is_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='is_current',
        ),
    ]
