# Generated by Django 5.0.7 on 2024-07-27 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_is_published_blogpost_published_and_more'),
        ('shop', '0007_remove_version_is_current'),
    ]

    operations = [
    ]
